### ISSUE TITLE
challenge on HFR assumes all deaths are within a hospital setting

### ISSUE THREAD

**Issue by avallecam** [epiverse-trace/tutorials-middle#24]
The challenge on HFR uses data from {covidregionaldata} country UK region England

Is it fair to assume that all deaths happened in a hospital setting? or in any case, would it be appropriate to add that explicit assumption?

- link to question: https://epiverse-trace.github.io/tutorials-middle/severity-static.html#hospitalisation-fatality-risk-hfr
- link to assumption pyramid: https://epiverse-trace.github.io/tutorials-middle/severity-static.html#data-sources-for-more-severity-measures

**Comment by pratikunterwegs** [comment]
I'm not really sure; I think that's a good question for {covidregionaldata} developers who know the package sources better than I do. As a starting point, I would assume that indeed most deaths happened in a hospital setting in England, but let's stick this on the Slack and get one of the PIs to weigh in.

**Comment by sbfnk** [comment]
There were quite a lot of deaths happening e.g. in care homes, and some at home, that didn't necessarily show up in the hospital data. If an assumption is made that all deaths showed up as hospitalisations I think it's worth writing that explicitly (and perhaps mention why it might be wrong).

**Comment by avallecam** [comment]
thank you for your replies. We'll need to edit it on #34 . 

I remember that I tried really hard to find a dataset with hospitalizations, but forgot about this assumption. If you recall an available data set (like a hospital linelist?) would be helpful for a simpler alternative. I agree to write the assumption, but may generate some confusion too. An alternative could also be to replace it with synthetic data.

**Comment by Bisaloo** [comment]
> An alternative could also be to replace it with synthetic data.

simulist is a good candidate for this. I believe it has all the features you need here and if not, your feedback can be a good source of improvement.

cc @joshwlambert

**Comment by avallecam** [comment]
> > An alternative could also be to replace it with synthetic data.
> 
> simulist is a good candidate for this. I believe it has all the features you need here and if not, your feedback can be a good source of improvement.
> 
> cc @joshwlambert

just tried {simulist} and filled a corresponding issue in https://github.com/epiverse-trace/simulist/issues/102 to try to get a similar scenario like the one above
