### ISSUE TITLE
epichains update

### ISSUE THREAD

**Issue by avallecam** [epiverse-trace/tutorials-middle#74]
modifications after epichains update

- [x] (1) index_cases to n_chains

  - we can simulate multiple chains within the 1 simulation

- [x] (2) we need to replace chain_id to `simulation_id` when using purrr

  - we make multiple simulations, instead of simulating multiple chains!
  - `simulate_chains()` simulate 1 chain or more
  - when we iterate `simulate_chains()`, we make multiple simulations of 1 chain or more

- [x] (3) update output column names

```r
# A tibble: 28 × 6
   chain infector infectee generation  time simulation_id
   <int>    <dbl>    <dbl>      <int> <dbl>         <int>
```

**Comment by jamesmbaazam** [comment]
Hey Andree, I was coming here to point this out after the [v0.1.0 release](https://github.com/epiverse-trace/epichains/releases/tag/v0.1.0). I would be happy to support if you need any help.

## plotting `<epichains>` objects

I also want to point out that you can now plot the `<epichains>` objects using `{epicontacts}`. There is a snippet of code in this issue https://github.com/epiverse-trace/epichains/issues/255 and a section in the [Getting Started vignette](https://epiverse-trace.github.io/epichains/articles/epichains.html#plotting). Note that if you don't want to go the route of subsetting the longest chain, you can simulate an outbreak with 1 case (`n_chains`) and create an `<epicontacts>` object directly from the resulting `<epichains>` object. If you want a big enough network, use the default `pop = Inf` and set a high `stat_max`. Please let me know if you need any help with this.
